import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { taskLists } from '@/libs/statics';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Index - Muhammad Kahfi NH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            {
              taskLists.map((task, index) => (
                <li key={index}>
                  Soal {index + 1}: 
                  <Link className={styles.taskLink} href={task.url} target={task.url === '/api/products' ? '_blank' : '_self'}>
                    {task.name}
                  </Link>
                </li>
              ))
            }
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://github.com/mokanh/nextjs-test-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Github Repo
            </a>
            <a
              href="https://mknh.dev/about"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Tentang Saya
            </a>
          </div>
        </main>
        <footer className={styles.footer} role="contentinfo">
          Aplikasi ini dibuat oleh Muhammad Kahfi NH untuk memenuhi syarat masuk PT. Mulya Kencana Metalindo
        </footer>
      </div>
    </>
  );
}
